NaturalDisaster7/2Q_AttackDefenceLog

- Engine/Engine.vcxproj
- Engine/Engine.vcxproj.filters
- Engine/Math/EasingFunction.cpp
- Engine/Math/EasingFunction.h
https://easings.net/ 참고사이트
float 변수 하나를 그래프처럼 변화시킬수 있음
> EasingFunction Engine-Math에 기능 추가

- Engine/Components/Camera/Camera.cpp
- Engine/Components/Camera/Camera.h
- WorkSpace/KJH/Script/MainCam.cpp
GetOffset(흔들림 크기 계산함수)에 scale보정식 추가
y값도 넘겨받도록해서 위아래, 좌우, 상하좌우로 흔들릴수있도록 수정
> 카메라 줌인 줌아웃 상태에서 흔들림 보정 추가

- Engine/Components/Rendering/ParticleRenderer.cpp
- WorkSpace/LSH/TestColliderApp/Scripts/DummyCircleCollider.cpp
baseScale의 값을 1.0f로 초기화 하도록 변경됨
> refactor - 파티클 decreasing할 때 이펙트 사라지는 버그 수정

- WorkSpace/ASB/Component/StateController.h
- WorkSpace/ASB/LiveObject/Player.cpp
- WorkSpace/ASB/LogicTestManager/AttackPatternManager.cpp
- WorkSpace/ASB/LogicTestManager/AttackPatternManager.h
- WorkSpace/ASB/LogicTestManager/BettleManager.cpp
플레이어 패턴 추가 1개 -> 2개
플레이어 패턴 같이 삭제하는 기능 추가
> 패턴 관련 기능 수정 및 추가

- Engine/Components/Rendering/ParticleRenderer.cpp
- Engine/Components/Rendering/ParticleRenderer.h
- Engine/Platform/D2DRenderManager.cpp
- Engine/Platform/D2DRenderManager.h
- WorkSpace/LSH/TestColliderApp/Scripts/DummyCircleCollider.cpp
1. SetAntialiasMode 함수 추가
2. CreateSpriteBatch 함수 추가
3. DrawSpriteBatch 함수 추가
> SpriteBatch 추가, ParticleRenderer 최적화 

- Contents/Scripts/CsvData/DataClass/EnemyData.cpp
- Contents/Scripts/LiveObject/Player.cpp
- Contents/Scripts/LogicManager/AttackPatternManager.cpp
- Contents/Scripts/LogicManager/AttackPatternManager.h
- Contents/Scripts/LogicManager/BettleManager.cpp
- Contents/Scripts/LogicManager/BettleManager.h
상중하 패턴에 따라 임의로 0.25배 차이로 데미지가 들어감
추후 추가사항 :
연격 -> 작업중
적 쿨타임 오류 수정하기
> 상중하 패턴에 따른 데미지 추가

- Contents/Objects/Common/MouseTrailObject.cpp
- Contents/Objects/Common/MouseTrailObject.h
- Contents/Objects/Common/PatternControlObject.cpp
- Contents/Objects/Common/PatternControlObject.h
- Contents/Scenes/MenuScene.cpp
- Engine/Components/Rendering/AnimatedChainEffect.cpp
- Engine/Components/Rendering/AnimatedChainEffect.h
- Engine/Components/Rendering/ChainDrawerComponent.cpp
- Engine/Components/Rendering/ChainDrawerComponent.h
> 애니메이트 체인 이펙트 컴포넌트 + 체인 드로우 컴포넌트 수정함

- WorkSpace/KJH/Script/Effect/EffectInstance.cpp
- WorkSpace/KJH/Script/Effect/EffectInstance.h
- WorkSpace/KJH/Script/Sound/SoundEnd.h
- WorkSpace/KJH/Script/Sound/SoundPlayScene.h
- WorkSpace/KJH/Script/Sound/SoundTittle.h
- WorkSpace/KJH/Script/TestObject.cpp
- WorkSpace/KJH/Script/TestObject.h
Effect에 Animation이펙트 추가, Animation 출력위치 지정 및 call함수 호출시 애니메이션 출력(설정된 duration만큼 재생후 종료)
> Effect에 Animation이펙트 추가

- Engine/Components/Rendering/VignetteEffect.cpp
- Engine/Components/Rendering/VignetteEffect.h
- Engine/Engine.vcxproj
- Engine/Engine.vcxproj.filters
- Engine/Platform/D2DRenderManager.cpp
- Engine/Platform/D2DRenderManager.h
- Engine/framework.h
- WorkSpace/LSH/LSH.vcxproj
- WorkSpace/LSH/LSH.vcxproj.filters
- WorkSpace/LSH/TestColliderApp/Scenes/CircleColliderScene.cpp
- WorkSpace/LSH/TestColliderApp/Scripts/TestVignetteObject.cpp
- WorkSpace/LSH/TestColliderApp/Scripts/TestVignetteObject.h
```
void TestVignetteObject::OnCreate()
{
vignette = owner->AddComponent<VignetteEffect>();
bitmap = owner->AddComponent<BitmapRenderer>();
}
void TestVignetteObject::OnStart()
{
bitmap->CreateBitmapResource(Singleton<AppPaths>::GetInstance().GetWorkingPath() + L"\\..\\..\\Resource\\Mouse\\testB.png");
vignette->SetBitmap(bitmap->GetResource()->GetBitmap().Get());
vignette->SetColor({ 1.0f, 0.0f,0.0f,1.0f });
vignette->SetEffectSize(0.8f);
vignette->SetStrength(0.4f);
vignette->SetOrderInLayer(10000);
}
```
> vignette 컴포넌트 추가

- Engine/Components/Fmod/FModComponent.cpp
- Engine/Components/Fmod/FModComponent.h
- WorkSpace/KJH/Script/Effect/EffectInstance.h
- WorkSpace/KJH/Script/Sound/SoundEnd.cpp
- WorkSpace/KJH/Script/Sound/SoundEnd.h
- WorkSpace/KJH/Script/Sound/SoundPlayScene.cpp
- WorkSpace/KJH/Script/Sound/SoundPlayScene.h
- WorkSpace/KJH/Script/Sound/SoundTittle.cpp
- WorkSpace/KJH/Script/Sound/SoundTittle.h
해당 Component를 추가하고 SetKeyHandle로 재생할 음악 설정 후 PlaySound();만 호출하면 음악 재생가능
전체 음악 멈춤 StopSound, 다시 재생은 PlayAgain();
> 각 Scene에서 사용할 음악 Component 추가

- Resource/Json/force_clash_spreadsheet_anim.json
- Resource/Json/force_clash_spreadsheet_sprites.json
> json 데이터 수정

- Engine/Components/UI/Slider.cpp
- Engine/Components/UI/Slider.h
- WorkSpace/KJH/Script/HpBar/HpGauge.cpp
- WorkSpace/KJH/Script/HpBar/HpGauge.h
- WorkSpace/KJH/Script/TestObject.cpp
오른쪽에서 왼쪽으로 감소하는거 이외에도 왼쪽에서 오른쪽으로 감소하는 기능 추가
HP게이지 수정
slider oncreate 추가
> fix - slider 좌우 반전 추가

- Contents/Objects/Common/PatternControlObject.cpp
- Contents/Scenes/TitleScene.cpp
- Contents/Scripts/Effect/Finaleffect.cpp
- Contents/Scripts/LogicManager/BettleManager.cpp
> 연격 마지막 이펙트 레이어 올림 + 벡터 뒤집음(기존 데이터 테이블-적공격과 반대로 출력되고 있었음)

- Contents/Scenes/Stage1.cpp
- Contents/Scenes/Stage2.cpp
- Contents/Scenes/Stage3.cpp
- Engine/Systems/AudioSystem.cpp
- Engine/Systems/AudioSystem.h
> fix - 오디오시스템 채널 삭제 오류수정 완료

- Contents/Scripts/Component/StateController.h
- Contents/Scripts/LiveObject/Enemy.cpp
- Contents/Scripts/LiveObject/Enemy.h
- Contents/Scripts/LiveObject/Player.cpp
- Contents/Scripts/LiveObject/Player.h
- WorkSpace/ASB/LiveObject/Enemy.cpp
feat - 적 움직임 추가(약식)
feat - 플레이어 움직임 추가
chore - 버그발견 : 적과 플레이어의 첫 노드가 같을 시 가드나 패링 처리되어버림
> feat - Fsm 에서 OnEnter, OnExit 추가 

- Contents/Scripts/LiveObject/Enemy.cpp
- Contents/Scripts/LiveObject/Player.cpp
- Contents/Scripts/LiveObject/Player.h
- Contents/Scripts/LogicManager/BettleManager.cpp
fix - 적의 연격 패턴으로는 플레이어가 죽지 않게 수정
> fix - 적 연격 이후에도  쿨타임 감소 적용되고 있음

- Contents/Objects/Common/BlinkNodeObject.cpp
- Contents/Objects/Common/BlinkNodeObject.h
- Contents/Objects/Common/PatternControlObject.cpp
- Contents/Objects/Common/PatternControlObject.h
- Contents/Scripts/LogicManager/BettleManager.cpp
> feat - 연격(적, 플레이어) 이후 1초간 노드 비활성화로 플레이 감성 보강

- Contents/Scenes/MenuScene.cpp
- Contents/Scripts/Effect/EnemyAttackEffect.cpp
- Contents/Scripts/Effect/EnemyAttackEffect.h
- Contents/Scripts/LiveObject/Enemy.cpp
> fix - 가드이펙트 오류 수정본

- Contents/Contents.vcxproj
- Contents/Contents.vcxproj.filters
- Contents/Scripts/Effect/EffectInstance2.cpp
- Contents/Scripts/Effect/EffectInstance2.h
> feat - 이펙트 2 추가

- Engine/Application/Application.cpp
- Engine/Application/Application.h
> feat - 프로그램 종료 코드 추가
